# .github/workflows/notify-top3-movers.yml
name: 'Notification: Top 3 Daily Movers (20:00 UTC)'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # A pnpm/action-setup lépést teljesen eltávolítottuk.
      # Helyette a standard Node.js beállítót használjuk npm gyorstárazással.
      - name: Setup Node.js and cache npm dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm' # MÓDOSÍTVA: a gyorstárazás most már 'npm'-re vonatkozik

      # A függőségek telepítése most már 'npm ci'-vel történik.
      # Ez a parancs a package-lock.json alapján dolgozik, gyors és megbízható.
      - name: Install dependencies
        run: npm ci

      # A szkript futtatása 'npx'-szel történik ('pnpm exec' helyett).
      - name: Run notification script for top 3 movers
        run: npx tsx scripts/sendNotifications.ts
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NOTIFICATION_TYPE: 'TOP_3_24H'