name: 'Notification: New Promotions (Every 3 hours)'

on:
  schedule:
    # Ellenőrzés minden 3 órában (GitHub Actions kvóta takarékosság)
    - cron: '0 */3 * * *'
  workflow_dispatch: # Manual trigger

jobs:
  notify-new-promotions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
        
    - name: Check for new promotions and send notifications
      run: npx tsx scripts/sendNotifications.ts
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NOTIFICATION_TYPE: 'NEW_PROMOTION'